apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-extractor
  template:
    metadata:
      labels:
        app: tweet-extractor
        env: local
    spec:
      containers:
        - name: app
          image: otonielsilva/tweet-extractor:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: twitter-api-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: tweet-extractor
spec:
  selector:
    app: tweet-extractor
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: twitter-api-credentials
type: Opaque
data:
  TOKEN_VALUE: {{TOKEN_VALUE}}
  TOKEN_SECRET: {{TOKEN_SECRET}}
  OAUTH_CONSUMER: {{OAUTH_CONSUMER}}
  OAUTH_ACCESS_TOKEN: {{OAUTH_ACCESS_TOKEN}}