name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven 
      run: ./mvnw -B package --file pom.xml -Ddocker.repository=otonielsilva/tweets-extractor
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login on docker hub
      uses: elgohr/Publish-Docker-Github-Action@master  
      with:
        registry: otonielsilva/tweets-extractor
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}

